export const __PUSH = 'COMMON_PUSH';
export const __POP = 'COMMON_POP';
export const __POP_TO = 'COMMON_POP_TO';
export const __RESET = 'COMMON_RESET';

export const __NAVIGATE = 'COMMON_NAVIGATE';

export const __REQUEST_START = 'COMMON_REQUEST_START';
export const __REQUEST_END = 'COMMON_REQUEST_END';
export const __REQUEST_ERROR = 'COMMON_REQUEST_ERROR';
export const __REQUEST_NETWORK_ERROR = 'COMMON_REQUEST_NETWORK_ERROR';
export const __ERROR_CLEARED = 'COMMON_ERROR_CLEARED';

export const __LOGGED_IN = 'COMMON_LOGGED_IN';
export const __LOGGED_OUT = 'COMMON_LOGGED_OUT';

export const __MENU_FETCHED = 'COMMON_MENU_FETCHED';
export const __ONE_TIMES_FETCHED = 'COMMON_ONE_TIMES_FETCHED';

export const __ORIENTATION_CHANGED = 'COMMON_ORIENTATION_CHANGED';
export const __LOCALE_UPDATED = 'COMMON_LOCALE_UPDATED';
export const __KEYBOARD_VISIBILITY_CHANGED = 'COMMON_KEYBOARD_VISIBILITY_CHANGED';

export const __PUSH_NOTIFICATION_GROUP_CHANGED = 'COMMON_PUSH_NOTIFICATION_GROUP_CHANGED';
export const __PUSH_NOTIFICATION_RECEIVED = 'COMMON_PUSH_NOTIFICATION_RECEIVED';

export const MINUTE_TICKED = 'COMMON_MINUTE_TICKED';

export const __UNDO = 'COMMON_UNDO';

export const __INIT = 'COMMON_INIT';

export const MODAL_SHOWN = 'COMMON_MODAL_SHOWN';
export const MODAL_DISMISSED = 'COMMON_MODAL_DISMISSED';